Major Cities/Areas Tested 
(only add to this list once you have reviewed all NPCs, shops, vehicle spawns, etc. as your class of civ/rebel, AFP or EMS):
	- Melbourne (as civ) [Woody]
	- Sydney (as civ) [Woody]
	- Brisbane (as civ) [Woody]
	- Cairns (as civ) [Woody]
	- Darwin (as civ) [Woody]
	- Northern Rebel Compound (as civ) [Woody]
	- South Rebel Outpost (as civ) [Woody]
	- Gang Hideout 3 (as civ) [Woody]
	- Perth (as civ) [Woody]
	
Map Problems :	
		-Adelaid DMV is floating
		-Adelaid Clothing store is floating
		-Adelaid General store is floating
		-Adelaid Bar needs to be moved. Standing in the bar table.
		-Adelaid Gas station door wont open
		-Blackmarket Trader @278080 - vehicle garage spawns off map.
		-Blackmarket Trader @278080 - vehicle shop/air garage spawns too close player/NPC.
		-Blackmarket Trader @278080 - weapon shop NPC is floating.
		-Melbourne General Store @314097 - NPC is floating.
		-Melbourne Aussie Oil @308098 - NPC is floating.
		-Melbourne Bottling Co. @308101 - No NPC (I assume this is a placeholder)
		-Melbourne Medical Assistance @311102 - NPC is floating.
		-SWAT Vendors @195243 - NPC's floating and clipping inside eachother
		-Sydney Iron/Copper Buyer @349117 - NPC is not at the desk.
		-Sydney Airport Plane Shop @351123 - NPC is floating.
		-Sydney Airport Helicopter Shop @352122 - NPC is not usable for civ.
		-Sydney Truck Shop @361121 - Vehicles Spawn too close to NPC.
		-Sydney Marina @369126 - Labelled as Sveneke Marina
		-Sydney Marina Boat Shop @369126 - NPC is in the water
		-Sydney Marina Boat Shop @369126 - NPC has option for "Nexoe Marina", should be "Boat Garage".
		-Sydney Heliport @365131 - Second helipad is not operational.
		-South Brisbane Brewery @384194 - No NPC (I assume this is a placeholder)
		-DP8 @386195 - NPC is in building wall.
		-Brisbane Truck Shop @382195 - Vehicles Spawn too close to NPC.
		-Brisbane Gas West @379197 - NPC is not located in the store.
		-Brisbane Carshop @383200 - There is no NPC.
		-Brisbane Hospital @380200 - EMS NPC is partially inside ATM.
		-Brisbane Garage @383202 - Garage and Car Shop NPCs are too close together.
		-Brisbane Airport @382206 - NPC is floating.
		-Toowoomba Tex's Gun Store @309200 - NPC is floating.
		-Toowoomba Gas @310201 - Labelled as "Pedersker Gas"
		-Toowoomba Gas @310201 - NPC is not located in the store.
		-Distillery @292233 - No NPC (I assume this is a placeholder).
		-DP12 @344244 - NPC is floating.
		-Cairns Airport @316309 - NPC is floating.
		-Gang Hideout 3 @291341 - No NPCs (I assume this is a placeholder).
		-DP16 @284352 - Has an NPC for a Gun Runner's Dealer.
		-Blackmarket Dealer @290365 - Shop named "Fancy Weapon Shop"
		-Blackmarket Dealer @290365 - NPC is floating.
		-Blackmarket Dealer @290365 - Non-floating NPC "Blackmarket Dealer" opens "Blackmarket Vehicle Shop"
		-Blackmarket Dealer @290365 - NPCs are not placed in Outpost compound.
		-Gun Runner's Dealer @234251 - No NPC
		-Darwin Gas Station @158334 - No market NPC
		-DP17 @164334 - Market NPC is next to delivery mission NPC.
		-Darwin Medical @166335 - No medical assistance NPC for healing.
		-Darwin Airport Plane NPC @167338 - Planes spawn too close to NPC and not on the runway.
		-Darwin Airport Plane NPC @167338 - NPC is floating.
		-Darwin Airport Helicopter NPC @167338 - Helicopter Shop is not usable for civ.
		-Chop Shop @101298 - NPC is not in chop shop compound.
		-Northern Rebel Compound @067256 - Rebel Special Weapons NPC opens Gun Runner's Dealer Shop.
		-Distillery @112186 - No NPC (I assume this is a placeholder).
		-South Rebel Outpost @142182 - New shop bought vehicles spawn too close to NPC.
		-South Rebel Outpost @142182 - Garage (air & land) retrieved vehicles spawn off map.
		-Perth Marina @042176 - NPC is floating.
		-Perth Marina @042176 - Unable to freshly spawned boat (until you go to boat and return to NPC)
		-Perth Marina @042176 - Ladder not usable and no nearby way to get out of water.
		-Perth Oil Processing @140176 - *License listed as 10K takes 28K
		-Perth Oil Processing @140176 - NPC is floating.
		-Perth Diving Shop @045177 - NPC is behind marina wall.
		-Perth Truck Shop @048177 - Vehicles spawn too close to NPC.
		-Perth Brewery @048180 - Labelled as Hasle Brewery.
		-Perth Airport Heli Shop @069180 - Vehicles spawn too close to NPC.
		-Perth Airport Heli Shop @069180 - No store vehicle option.
		-Perth Airport Plane Shop @068181 - NPC floating.
		-Perth Airport Heliport @067180 - Second heli pad spawn point not working.
		-Perth Medical Center @056183 - EMS NPC is floating.
		-Perth Medical Center @055183 - Medical Assistance NPC is floating.
		-Perth Car Shop @053184 - NPCs are in the road the siding. Australia Map v3 change?
		-Perth National Bank @056184 - Labelled as Sydney National Bank.
		-Perth Gas East @055187 - Not located inside store.
		
